#+TITLE: The stack order
#+SUBTITLE: or, Why it doesn't matter
* The algorithm doesn't care
- I have discussed how HETI calculates global unhappiness and tries to
  minimise it in the allocation process in a [[file:readme.org][separate article]]
- This is meant more as an endnote to that one
- I will attempt to explain why the exact order of the stack makes no
  difference
* Consensus reality
- If we imagine our algorithm as a jet-powered bouncy ball bouncing
  through a landscape, the algorithm basically jumps and bounces over
  its hills and valleys until the rocket runs out of steam and falls
  into the deepest valley.
- It calculates your unhappiness based on what position the hospital
  you got allocated to is in your preference list.
- The natural consequence of this is that the only meaningful benefit
  of the stack is when used in combination with placing your favourite
  hospital first, as it essentially forces the system to reduce
  unhappiness by moving people into their first preferences
- If you don't get your first preference, what hospital you get
  instead essentially comes down to random chance. If everyone has the
  same preference list, there is, by and large, no particular
  advantage to swapping anyone from a non-first preference to a
  non-first preference.
- Broadly speaking: *the only requirement for the stack to serve its
  functional purpose, is for there to be a consensus on exactly what
  the order of the stack is.*
- And for that reason, any attempt to change the exact order of the
  stack, unless universally accepted, is frivolous. It may even be seditious.
* Updates to come
Suggest more on Github or via PM/comment
- [ ] Maths for nerds
- [ ] Addressing proposals to change the stack
  - [ ] Hornsby vs Westmead
  - [ ] RNS vs RPA
- [ ] Effect of consensus-breaking on placement
  - [ ] By proportion and number of variant stacks
- [ ] Is the stack just a myth?
